services:
  grafana:
    image: grafana/grafana
    depends_on:
      - database
    ports:
      - "3000:3000"
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mrat4D0uiI"
      POSTGRES_USER: grafana
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data:
