name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - 'all/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'all/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file all/pom.xml
