name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - 'all/**'
      - 'codingame/**'
      - 'craftinginterpreters/**'
      - 'web/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - 'all/**'
      - 'codingame/**'
      - 'craftinginterpreters/**'
      - 'web/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'temurin'
        cache: maven
    - run: mvn --batch-mode verify
