name: extreme_startup-http4s

on:
  push:
    branches: [ main ]
    paths:
      - 'extreme_startup-http4s/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'extreme_startup-http4s/**'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - run: sbt scalafmtCheckAll compile undeclaredCompileDependenciesTest unusedCompileDependenciesTest
        working-directory: extreme_startup-http4s
